//! Self-diagnostics — run internal checks, report issues to GitHub.
//! NEVER includes sensitive data (tokens, keys, user content).

#[path = "diagnostics_checks.rs"]
mod diagnostics_checks;

use reqwest::Client;
use serde::{Deserialize, Serialize};

pub use diagnostics_checks::run_diagnostics;

/// Result of a single diagnostic check.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DiagCheck {
    pub name: String,
    pub passed: bool,
    pub message: String,
    pub duration_ms: u64,
}

/// Full diagnostics report.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DiagReport {
    pub version: String,
    pub platform: String,
    pub checks: Vec<DiagCheck>,
    pub passed: usize,
    pub failed: usize,
    pub timestamp: String,
}

/// Create a GitHub issue for diagnostic failures.
/// CRITICAL: Never includes sensitive data (tokens, keys, paths with usernames).
pub async fn create_github_issue(report: &DiagReport, gh_token: &str) -> Result<String, String> {
    let failures: Vec<_> = report.checks.iter().filter(|c| !c.passed).collect();

    if failures.is_empty() {
        return Err("No failures to report".into());
    }

    let title = format!(
        "[auto-diag] {} failure(s) on {} v{}",
        failures.len(),
        sanitize_platform(&report.platform),
        report.version,
    );

    let body = format!(
        "## Automated Diagnostics Report\n\n\
         **Version**: {}\n\
         **Platform**: {}\n\
         **Timestamp**: {}\n\
         **Checks**: {} passed, {} failed\n\n\
         ### Failures\n\n{}\n\n\
         ### All Checks\n\n{}\n\n\
         ---\n\
         *Auto-generated by `convergio diagnostics`. No sensitive data included.*",
        report.version,
        sanitize_platform(&report.platform),
        report.timestamp,
        report.passed,
        report.failed,
        failures
            .iter()
            .map(|c| format!("- **{}**: {}", c.name, sanitize(&c.message)))
            .collect::<Vec<_>>()
            .join("\n"),
        report
            .checks
            .iter()
            .map(|c| {
                let icon = if c.passed { "pass" } else { "FAIL" };
                format!(
                    "| {} | {} | {} | {}ms |",
                    icon,
                    c.name,
                    sanitize(&c.message),
                    c.duration_ms
                )
            })
            .collect::<Vec<_>>()
            .join("\n"),
    );

    let client = Client::new();
    let resp = client
        .post("https://api.github.com/repos/Roberdan/convergio/issues")
        .header("Authorization", format!("Bearer {gh_token}"))
        .header("User-Agent", "convergio-diag")
        .header("Accept", "application/vnd.github+json")
        .json(&serde_json::json!({
            "title": title,
            "body": body,
            "labels": ["auto-diagnostics", "bug"],
        }))
        .send()
        .await
        .map_err(|e| format!("HTTP error: {e}"))?;

    if resp.status().is_success() {
        let json: serde_json::Value = resp.json().await.map_err(|e| format!("JSON error: {e}"))?;
        let url = json["html_url"].as_str().unwrap_or("unknown");
        Ok(url.to_string())
    } else {
        Err(format!("GitHub API error: HTTP {}", resp.status()))
    }
}

/// Strip sensitive information from diagnostic messages.
fn sanitize(s: &str) -> String {
    // Remove potential file paths with usernames
    let s = regex_lite_replace_home(s);
    // Redact anything that looks like a token/key/secret
    // These are DETECTION PATTERNS for redacting leaked secrets in diagnostic output,
    // NOT actual secret values.
    // CodeQL: lgtm[rust/hard-coded-cryptographic-value]
    const PATTERNS: &[&str] = &[
        "sk-",    // Anthropic/OpenAI
        "ghp_",   // GitHub PAT
        "gho_",   // GitHub OAuth
        "Bearer", // Auth headers
        "AKIA",   // AWS
        "xoxb-",  // Slack
        "eyJ",    // JWT (base64 encoded)
        "token=", // Query string tokens
    ];
    if PATTERNS.iter().any(|p| s.contains(p)) || s.len() > 200 {
        return "[redacted]".to_string();
    }
    s
}

fn sanitize_platform(p: &str) -> String {
    // Platform triple is safe to share
    p.to_string()
}

fn regex_lite_replace_home(s: &str) -> String {
    // Replace /Users/username or /home/username with ~
    if let Some(home) = dirs::home_dir() {
        let home_str = home.to_string_lossy();
        return s.replace(home_str.as_ref(), "~");
    }
    s.to_string()
}
